id: P009456
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:39:38.517381
source_metadata:
  id: bdr:W25052
  title: བོད་ཀྱི་སྙན་ངག་གི་མཛེས་ཉམས
  author: ''
  volumes:
    e84f268aedef4bbc9a0acd336ba38e95:
      image_group_id: I1PD350
      title: ''
      volume_number: 1
      total_pages: 418
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
