id: I7951A66A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:12:18+00:00'
last_modified: '2022-06-08T11:10:16.659085+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25052
  title: བོད་ཀྱི་སྙན་ངག་གི་མཛེས་ཉམས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7EB0:
      image_group_id: I1PD350
      title: ''
      total_pages: 418
      order: 1
      base_file: 7EB0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
